### ISSUE TITLE
Implement basic unit test coverage for data integration Python modules

### ISSUE THREAD

**Issue by justinlewis** [justinlewis/climbmapper#24]

**Comment by justinlewis** [comment]
Can we close this?  Seems like our Python test coverage is 100% better than it was :)

**Comment by brendonakay** [comment]
I would say this is safe to close. I'm going to spend more time updating the unit tests (of course) but I'd like to take a test driven approach to the data side of Climbmapper. This way we can have a clearly defined set of requirements for the APIs we plan on implementing in the future.
